language: node_js
node_js:
  - "5.11"
cache:
  directories:
    - node_modules
install:
  - npm install
env:
  - TEST_TYPE=lint
  - TEST_TYPE=test
  - TEST_TYPE=e2e-test
script:
  - npm run $TEST_TYPE
